apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agenda-api-uploads
  namespace: agenda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # k3s 自带 local-path-provisioner，storageClassName 为 local-path
  storageClassName: local-path
